version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: vanducng/reverseproxy
  backend_user:
    build:
      context: ../../restapi-user
    image: vanducng/restapi-user
  backend_feed:
    build:
      context: ../../restapi-feed
    image: vanducng/restapi-feed
  frontend:
    build:
      context: ../../frontend
    image: vanducng/frontend
